export const cards = [
  {
    title: "Аурелия ир'Винарн (Aurelia ir'Wynarn)",
    desc: "Королева Аундаира",
    img: "https://i.ibb.co/zshv4sp/BXDK7-G3-Imgur.jpg",
    imgFull: "https://i.ibb.co/MnD0Cnr/BXDK7-G3-Imgur.jpg",
    tags: {
      "Age": "37",
      "Gender": "Женский",
      "Race": "Человек",
      "Home": "Fairhaven, Аундаир",
      "Organisation": "Аундаир",
    },
    boolTags: {
      "Major": false,
      "Alive": true
    },
    hidden: false,
  },
  {
    title: "Фарвен (Farven)",
    desc: "Шпион Палаты в Двенадцать",
    img: "https://i.ibb.co/SrM5bP6/090c5373c69d0d74ea3e0a3840c9eb4c.jpg",
    imgFull: "https://i.ibb.co/vYTVpHc/090c5373c69d0d74ea3e0a3840c9eb4c.jpg",
    tags: {
      "Age": ">100",
      "Gender": "Мужской",
      "Race": "Эльф",
      "Home": "—",
      "Organisation": "Палата",
    },
    boolTags: {
      "Major": false,
      "Alive": false
    },
    hidden: false,
  },
  {
    title: "Меррикс д'Каннит (Merrix d'Cannith)",
    desc: "Барон Южного Анклава Дома Каннит",
    img: "https://i.ibb.co/ZKg7qfk/e20ca86f7a72f736079ac1eed1d51b25.jpg",
    imgFull: "https://i.ibb.co/ftNLjXP/e20ca86f7a72f736079ac1eed1d51b25.jpg",
    tags: {
      "Age": "27",
      "Gender": "Мужской",
      "Race": "Человек",
      "Home": "Башня Каннит, Шарн",
      "Organisation": "Дом Каннит (Южный Анклав)",
    },
    boolTags: {
      "Major": true,
      "Alive": true
    },
    hidden: false,
  },
  {
    title: "Джорланна д'Каннит (Jorlanna d'Cannith)",
    desc: "Баронесса Западного Анклава Дома Каннит",
    img: "https://i.ibb.co/mDVwSqJ/wieke-pratiwi-prabowo-witcher-inspired-oc-2.jpg",
    imgFull: "https://i.ibb.co/5Mgy28T/wieke-pratiwi-prabowo-witcher-inspired-oc-2.jpg",
    tags: {
      "Age": "57",
      "Gender": "Женский",
      "Race": "Человек",
      "Home": "Fairhaven, Аундаир",
      "Organisation": "Дом Каннит",
    },
    boolTags: {
      "Major": false,
      "Alive": false
    },
    hidden: false,
  }
]

export const oldChars = [
  {
    name: "Боранел ир'Винарн (Boranel ir'Wynarn)",
    desc: "Король Бреландии",
    "Age": "71",
    "Gender": "Мужской",
    "Race": "Мужской",
    "Home": "Wroat, Бреландия",
    img: "https://i.ibb.co/jLGL8Q9/Boranel.jpg",
    addDesc: "",
    "Organisation": "Бреландия",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Арриас (Arrias)",
    desc: "Странствующий(-ие?) торговец(-цы?)?",
    "Age": "?",
    "Gender": "Мужской?",
    "Race": "Тифлинг?",
    "Home": "?",
    img: "https://i.ibb.co/m6MsSNk/pathfinder-nirukni-alchemist-of-shax-by-willobrien-da2rz1b-fullview.jpg",
    addDesc: "",
    "Organisation": "?",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Целирия ир'Тэйн (Celyria ir'Tain)",
    desc: "Главная Леди Шарна",
    "Age": "37",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "Скайвэй, Шарн",
    img: "https://i.ibb.co/x2D5K7h/aizel-kon.jpg",
    addDesc: "",
    "Organisation": "Шарн, Тэйны",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Гримунд Солдорак (Grymund Soldorak)",
    desc: "Генерал клана Солдорак",
    "Age": ">150",
    "Gender": "Мужской",
    "Race": "Дварф",
    "Home": "Krona Peak, Чертоги Мрора",
    img: "https://i.ibb.co/Nj26hht/5efde0fdc378c-91c90871bc233165e716181e7a6233cb.png",
    addDesc: "",
    "Organisation": "Чертоги Мрора, Клан Солдорак",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Кайус III ир'Винарн (Kaius III ir'Wynarn)",
    desc: "Король Каррната",
    "Age": "53 (178?)",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "Корт, Каррнат",
    img: "https://i.ibb.co/y44cSDh/juyoung-ha-untitle-3.jpg",
    addDesc: "",
    "Organisation": "Каррнат",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Кванти д'Ориен (Kwanti d'Orien)",
    desc: "Матриарх Дома Ориен",
    "Age": "48",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "Passage, Аундаир",
    img: "https://i.ibb.co/LJ4kpv2/041-1-27.png",
    addDesc: "",
    "Organisation": "Дом Ориен",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Рессиса д'Медани (Ressysa d'Medani)",
    desc: "Представительница дома Медани и текущая глава совета Двенадцати",
    "Age": "~45",
    "Gender": "Женский",
    "Race": "Полуэльф (Коравар)",
    "Home": "—",
    img: "https://i.ibb.co/6BPW6hk/5efb35bf5e9d6-z-Fw-Bby1.png",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": true,
    dead: true
  },
  {
    name: "Рирдар Риста (Rirdar Rista)",
    desc: "???",
    "Age": "~70?",
    "Gender": "Мужской?",
    "Race": "Человек?",
    "Home": "???",
    img: "https://i.ibb.co/N2D1Zs9/jr-Sux3xj-AKapm5iv-OH5-DAil-TUs-ACCJ9-BCIWqq-Oh-D.jpg",
    addDesc: "",
    "Organisation": "Палата?",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Шасса Тарр (Shassa Tarr)",
    desc: "Член Совета Шарна (Lower Northedge)",
    "Age": "~40",
    "Gender": "Женский",
    "Race": "Шифтер",
    "Home": "Нижний Northegde, Шарн",
    img: "https://i.ibb.co/fqT8rY8/205a865f61ffcb84b3336164340a2330.jpg",
    addDesc: "Член Совета Шарна (Lower Northedge), Глава и представитель шифтерского сообщества в Шарне (и в Совете), Член Аурума",
    "Organisation": "Шарн, Аурум",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Тиотас д'Денейт (Tiotas d'Deneith)",
    desc: "Представитель дома Денейт",
    "Age": "~40",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "—",
    img: "https://i.ibb.co/34L2msH/7ef6df2a0c052cccf8ac61f78f9b4f8e.jpg",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": false,
    dead: true
  },
  {
    name: "Вум Менкрад д'Ориен (Vum Menkrad d'Orien)",
    desc: "Представительница дома Ориен",
    "Age": "~40",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "—",
    img: "https://i.ibb.co/12tFwPS/4fb0c6d9c1245358ab1af226df8dbad4.jpg",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": false,
    dead: true
  },
  {
    name: "Занрил д'Лирандар (Zanril d'Lyrandar)",
    desc: "Представитель дома Лирандар",
    "Age": "~50",
    "Gender": "Мужской",
    "Race": "Полуэльф (Коравар)",
    "Home": "—",
    img: "https://i.ibb.co/7SFsCWZ/9f193fb4082da3c8db4d32cb55f93493.png",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": false,
    dead: true
  },
  {
    name: "Зорлан д'Каннит (Zorlan d'Cannith)",
    desc: "Барон Восточного Анклава Дома Каннит",
    "Age": "52",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "Корт, Каррнат",
    img: "https://i.ibb.co/qjv5pfT/younghun-byun-f-1-v.jpg",
    addDesc: "",
    "Organisation": "Дом Каннит",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Явик Лапвункрект",
    desc: "Исследователь Драконьих Предсказаний",
    "Age": "~27",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "???",
    img: "https://i.ibb.co/Q6KF7RF/b986ba5d74325ab7c785b4858004b846.jpg",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Мирол д'Ориен (Mirol d'Orien)",
    desc: "Дочь Кванти",
    "Age": "~20",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "?",
    img: "https://i.ibb.co/Lk7Q1Rs/46f95a48b15e709e28f9ae36c74eb0b7.jpg",
    addDesc: "",
    "Organisation": "",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Ол ир'Грик (Ol ir'Grik)",
    desc: "Аристократ, спасённый в Скорби",
    "Age": "~50",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "Flamekeep, Трейн",
    img: "https://i.ibb.co/7rP2qY4/image0.jpg",
    addDesc: "",
    "Organisation": "",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Веро (Vero)",
    desc: "Артифишер-электрик",
    "Age": "~25",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "Университет Моргрейв, Шарн",
    img: "https://i.ibb.co/kSD6Pn8/096-416.png",
    addDesc: "",
    "Organisation": "",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Бехмед д'Вадалис (Behmed d'Vadalis)",
    desc: "Глава Экспериментальных Разработок Дома Вадалис в Шарне",
    "Age": "~45",
    "Gender": "Мужской",
    "Race": "Человек",
    "Home": "Башня Вадалис, Шарн",
    img: "https://i.ibb.co/tpZQNXq/157ea79d7c1307a50fcc389a794b3e8c.png",
    addDesc: "",
    "Organisation": "Дом Вадалис",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Эйрнан Ки (Eirnan Ki)",
    desc: "Варлок из Круга Ауреона",
    "Age": "~25",
    "Gender": "Мужской",
    "Race": "Полуэльф (Коравар)",
    "Home": "Круг Ауреона, Шарн",
    img: "https://i.ibb.co/g9dchp2/d787d349553213e7016dfafd6d532453.png",
    addDesc: "",
    "Organisation": "Круг Ауреона",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Гли Зетиш (Glee Zetish)",
    desc: 'Дипломат из города тифлингов "Ядовитые Владения" в Дроааме',
    "Age": "~30",
    "Gender": "Женский",
    "Race": "Тифлинг",
    "Home": "Дроаам, Ядовитые Владения",
    img: "https://i.ibb.co/sJpX5xt/image.png",
    addDesc: "",
    "Organisation": "Ядовитые Владения",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Эльвинора Элорренти д'Фиарлан (Elvinora Elorrenthi d'Phiarlan)",
    desc: "Матриарх Дома Фиарлан",
    "Age": ">600",
    "Gender": "Женский",
    "Race": "Эльф",
    "Home": "Башня Фиарлан, Шарн",
    img: "https://i.ibb.co/kKJj8V5/unknown.png",
    addDesc: "",
    "Organisation": "Дом Фиарлан",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Трелиб д'Медани (Trelib d'Medani)",
    desc: "Патриарх Дома Медани",
    "Age": "123",
    "Gender": "Мужской",
    "Race": "Полуэльф (Коравар)",
    "Home": "Wroat, Бреландия",
    img: "https://i.ibb.co/pjSLcsb/Trelib.png",
    addDesc: "",
    "Organisation": "Дом Медани",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Чайли",
    desc: "Друид из Элдинских Пределов",
    "Age": "?",
    "Gender": "Женский",
    "Race": "Фирболг",
    "Home": "Элдинские Пределы",
    img: "https://i.ibb.co/Jdgxz1m/af90507a4349f0947b72e9f36647f483.png",
    addDesc: "",
    "Organisation": "Элдинские Пределы",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Мала Боромар д’Джораско (Mala Boromar d'Jorasco)",
    desc: "Матриарх клана Боромар",
    "Age": "61",
    "Gender": "Женский",
    "Race": "Полурослик",
    "Home": "Callestan, Шарн",
    img: "https://i.ibb.co/GRWVWxR/image0.jpg",
    addDesc: "",
    "Organisation": "Боромары",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Илира Боромар (Ilyra Boromar)",
    desc: "Член Совета Шарна (Нижняя Dura), старшая наследница клана Боромар",
    "Age": "37",
    "Gender": "Женский",
    "Race": "Полурослик",
    "Home": "Callestan, Шарн",
    img: "https://i.ibb.co/thKnjKT/123123.jpg",
    addDesc: "",
    "Organisation": "Боромары",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Сэйдан Боромар (Saidan Boromar)",
    desc: "Патриарх клана Боромар",
    "Age": "83",
    "Gender": "Мужской",
    "Race": "Полурослик",
    "Home": "Callestan, Шарн",
    img: "https://i.ibb.co/pbMNCgf/cfc82d32a348f1d7e82c287e6a671deb.jpg",
    addDesc: "",
    "Organisation": "Боромары",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Оринан д'Лирандар",
    desc: "Ученик Сигил",
    "Age": "23",
    "Gender": "Мужской",
    "Race": "Полуэльф (Коровар)",
    "Home": "Шарн, Бреландия",
    img: "https://i.ibb.co/GJwWByz/f459d03e2fd65cd1a8cb9e365b8b9e27.png",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Сарлена Долдарун",
    desc: "Ученица Кремня",
    "Age": "33",
    "Gender": "Женский",
    "Race": "Дварфийка",
    "Home": "Шарн, Бреландия",
    img: "https://i.ibb.co/2dtbQYW/IMG-4809.jpg",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Орхани Элайра ир'Корран",
    desc: "Ученица Могрейн",
    "Age": "29",
    "Gender": "Женский",
    "Race": "Гном",
    "Home": "Шарн, Бреландия",
    img: "https://i.ibb.co/jHZV3Yt/IMG-4810-PNG.jpg",
    addDesc: "",
    "Organisation": "Двенадцать",
    hidden: false,
    "Major": true,
    dead: false
  },
  {
    name: "Зани д'Каннит (Zani d'Cannith)",
    desc: "Сестра Меррикса; Глава Академии Мира им. Аарена",
    "Age": "29",
    "Gender": "Женский",
    "Race": "Человек",
    "Home": "Башня Каннит, Шарн",
    img: "https://i.ibb.co/B6r5Djg/9HXF0Yg.png",
    addDesc: "",
    "Organisation": "Дом Каннит (Южный Анклав)",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Моррикан д'Кундарак (Morrikan d'Kundarak)",
    desc: "Патриарх Дома Кундарак",
    "Age": "199",
    "Gender": "Мужской",
    "Race": "Дварф",
    "Home": "Korunda Gate, Чертоги Мрора",
    img: "https://i.ibb.co/gVBc1wh/73c7dc1f84344895d581c9391f6579ea.jpg",
    addDesc: "",
    "Organisation": "Дом Кундарак",
    hidden: true,
    "Major": false,
    dead: false
  },
  {
    name: "Верван Рог (Vervan Rog)",
    desc: "Начальник охраны Двенадцати; агент Палаты?",
    "Age": "~35",
    "Gender": "Мужской",
    "Race": "Человек (Денейт)",
    "Home": "Корт, Каррнат",
    img: "https://i.ibb.co/BP77fWn/aurore-folny-7-arthos.jpg",
    addDesc: "",
    "Organisation": "Палата?",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: "Фарнан Орувор д'Сивис (Farnan Oruwor d'Sivis)",
    desc: "Помощник Партии в Драконьем Дозоре",
    "Age": "129",
    "Gender": "Мужской",
    "Race": "Гном",
    "Home": "Шарн, Бреландия",
    img: "https://i.ibb.co/FXQNC1N/image0.jpg",
    addDesc: "",
    "Organisation": "Драконий Дозор, Двенадцать",
    hidden: true,
    "Major": false,
    dead: false
  },
  {
    name: "Тадиса Лирриман д'Сивис (Tadysa Lyrriman d'Sivis )",
    desc: "Вторая помощница Партии в Драконьем Дозоре",
    "Age": "31",
    "Gender": "Женский",
    "Race": "Гном",
    "Home": "Шарн, Бреландия",
    img: "https://i.ibb.co/2t07fVn/image0.jpg",
    addDesc: "",
    "Organisation": "Драконий Дозор, Двенадцать",
    hidden: false,
    "Major": false,
    dead: false
  },
  {
    name: 'Грарос “Левиафан” Глин (Graror "Leviathan" Glin)',
    desc: "Знаменитый пират (заточен в Дредхолде)",
    "Age": "28",
    "Gender": "Мужской",
    "Race": "Полуэльф (Коравар)",
    "Home": "Дредхолд",
    img: "https://i.ibb.co/VxqTTJt/g-ZGv2-Jb-e8-Oz-Y56-XUi-NKyr-Rg-B0-Mg-Crefw-mlm-WQg-Zm4.jpg",
    addDesc: "",
    "Organisation": "Лаазарские Княжества",
    hidden: false,
    "Major": false,
    dead: false
  },
];